<?php

/*
    ================
    == Sessions ==
    ================
    - Session Is Stored On The Server
    - Session Store Only  A User Key In Cookie To Know Its You
    - Key Are Generated By PHP Engine Its Almost Impossible To Guess 
    - You Need To Add It Before Any Output
 */

// session_id("mosdn21251df"); // When creating your own key . Note => when creating the key created before  

session_start();
// echo session_id(); // b2ka4tticulmv2083s8q8aejt9

$_SESSION["Name"] = "Mohammed";
$_SESSION["Id"]   = 10;


echo "<pre>";
print_r($_SESSION);
/*
Array
(
    [Name] => Mohammed
    [Id] => 10
)
*/
echo "</pre>";



// example 2 => Views Count

isset($_SESSION['views']) ? $_SESSION['views']++ : $_SESSION['views'] = 1;

echo "Hello =>  {$_SESSION['Name']}  Views Count Is =>  {$_SESSION['views']} <br> 
<a href='test.php'>Test</a>";


echo '<br>';

echo "\\*==============================*\\<br>";


/*
    ================
    == Sessions ==
    ================
    - Unset And Destroy
    - Login And Logout Simulation 

        - Example Login And Logout
 */


if ($_SERVER["REQUEST_METHOD"] === "POST") {
    if ($_POST["user"] === "Mohammed") {
        $_SESSION["Auth"]   = "Mohammed";
        $_SESSION["AuthId"] = 20;
    } else {
        echo "<h4 style='color: red;'> Username error </h4>";
    }
}

if (isset($_SESSION["Auth"])) {
    echo "Welcome {$_SESSION['Auth']} <br> And ID => {$_SESSION['AuthId']} <br> <a href='logout.php'>Logout</a>";
} else { ?>
    <form action="" method="POST">
        <input type="text" name="user">
        <input type="submit" value="Login">
    </form>
<?php
}
?>